version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.node
    networks:
      - backend_backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/home/node/app

networks:
  backend_backend:
    external: true